name: plant_disease_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - pip
  - pip:
      - mlflow
      - tensorflow[and-cuda]  # عشان يدعم الـ GPU في WSL أو Linux
      - matplotlib
      - numpy
      - pandas
      - pillow
      - scikit-learn
      - ipykernel


